package commands

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var (
	initForce bool
)

// initCmd represents the init command
var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize nomad-changelog configuration",
	Long: `Interactive setup wizard to create a configuration file.

This command guides you through creating a nomad-changelog.toml configuration
file with all the necessary settings to connect to Nomad and your Git repository.

If a configuration file already exists, use --force to overwrite it.`,
	RunE: initRun,
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing configuration file")
	rootCmd.AddCommand(initCmd)
}

func initRun(cmd *cobra.Command, args []string) error {
	configPath := "nomad-changelog.toml"
	if cfgFile != "" {
		configPath = cfgFile
	}

	// Check if config already exists
	if _, err := os.Stat(configPath); err == nil && !initForce {
		PrintWarning(fmt.Sprintf("Configuration file already exists: %s", configPath))
		fmt.Println("Use --force to overwrite it, or edit it manually.")
		fmt.Println("\nTo verify your configuration, run:")
		fmt.Println("  nomad-changelog config check")
		return nil
	}

	PrintInfo("🚀 Welcome to nomad-changelog setup!")
	fmt.Println()
	fmt.Println("This wizard will help you create a configuration file.")
	fmt.Println()

	reader := bufio.NewReader(os.Stdin)

	// Choose backend
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("📦 Backend Selection")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("Choose a backend for storing job configurations:")
	fmt.Println("  1) Git Backend (default) - Works with any Git provider (GitHub, GitLab, etc.)")
	fmt.Println("     • Maintains local repository")
	fmt.Println("     • Supports SSH and HTTPS authentication")
	fmt.Println("     • Best for local development")
	fmt.Println()
	fmt.Println("  2) GitHub API Backend - Direct GitHub API integration")
	fmt.Println("     • No local repository (stateless)")
	fmt.Println("     • Requires GitHub token")
	fmt.Println("     • Best for CI/CD environments")
	fmt.Println()

	backend := promptChoice(reader, "Select backend", []string{"git", "github-api"}, "git")

	var config strings.Builder
	config.WriteString("# nomad-changelog configuration\n")
	config.WriteString("# Generated by: nomad-changelog init\n\n")

	// Git/Backend configuration
	config.WriteString("# Storage backend configuration\n")
	config.WriteString("[git]\n")
	config.WriteString(fmt.Sprintf("backend = \"%s\"\n", backend))

	if backend == "git" {
		configureGitBackend(reader, &config)
	} else {
		configureGitHubAPIBackend(reader, &config)
	}

	// Nomad configuration
	fmt.Println()
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("🎯 Nomad Configuration")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()

	nomadAddr := prompt(reader, "Nomad address", "http://localhost:4646")
	config.WriteString("\n# Nomad cluster configuration\n")
	config.WriteString("[nomad]\n")
	config.WriteString(fmt.Sprintf("address = \"%s\"\n", nomadAddr))
	config.WriteString("# token = \"\"  # Or set NOMAD_TOKEN environment variable\n")

	// Jobs configuration
	fmt.Println()
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("📋 Jobs to Track")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("You can add jobs to track now, or add them later by editing the config file.")

	addJobs := promptYesNo(reader, "Add jobs now?", true)

	config.WriteString("\n# Jobs to track\n")

	if addJobs {
		jobNum := 1
		for {
			fmt.Println()
			jobName := prompt(reader, fmt.Sprintf("Job %d name (empty to finish)", jobNum), "")
			if jobName == "" {
				break
			}

			namespace := prompt(reader, "  Namespace", "default")

			config.WriteString("[[jobs]]\n")
			config.WriteString(fmt.Sprintf("name = \"%s\"\n", jobName))
			config.WriteString(fmt.Sprintf("namespace = \"%s\"\n", namespace))
			config.WriteString("\n")

			jobNum++
		}

		if jobNum == 1 {
			config.WriteString("# [[jobs]]\n")
			config.WriteString("# name = \"my-job\"\n")
			config.WriteString("# namespace = \"default\"\n")
		}
	} else {
		config.WriteString("# [[jobs]]\n")
		config.WriteString("# name = \"my-job\"\n")
		config.WriteString("# namespace = \"default\"\n")
	}

	// Write config file
	if err := os.WriteFile(configPath, []byte(config.String()), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	// Success message
	fmt.Println()
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	PrintSuccess(fmt.Sprintf("✅ Configuration saved to: %s", configPath))
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()

	// Next steps
	fmt.Println("📝 Next Steps:")
	fmt.Println()

	if backend == "git" {
		fmt.Println("1. Set up Git authentication:")
		fmt.Println("   • For SSH: Ensure your SSH key is added to your Git provider")
		fmt.Println("   • For HTTPS: Set GITHUB_TOKEN environment variable")
	} else {
		fmt.Println("1. Set your GitHub token:")
		fmt.Println("   export GITHUB_TOKEN=\"ghp_your_token_here\"")
	}

	fmt.Println()
	fmt.Println("2. Verify your configuration:")
	fmt.Println("   nomad-changelog config check")
	fmt.Println()
	fmt.Println("3. Start syncing:")
	fmt.Println("   nomad-changelog sync")
	fmt.Println()

	return nil
}

func configureGitBackend(reader *bufio.Reader, config *strings.Builder) {
	fmt.Println()
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("🔧 Git Backend Configuration")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()

	fmt.Println("Examples:")
	fmt.Println("  SSH:   git@github.com:myorg/nomad-jobs.git")
	fmt.Println("  HTTPS: https://github.com/myorg/nomad-jobs.git")
	gitURL := prompt(reader, "Git repository URL", "")

	branch := prompt(reader, "Branch", "main")

	fmt.Println()
	fmt.Println("Authentication method:")
	fmt.Println("  • ssh: Use SSH keys (recommended for local development)")
	fmt.Println("  • token: Use personal access token (recommended for CI/CD)")
	fmt.Println("  • auto: Try SSH first, fall back to token")
	authMethod := promptChoice(reader, "Authentication method", []string{"auto", "ssh", "token"}, "auto")

	localPath := prompt(reader, "Local repository path", ".")
	repoName := prompt(reader, "Repository directory name", "nomad-changelog-repo")

	authorName := prompt(reader, "Git commit author name", "nomad-changelog")
	authorEmail := prompt(reader, "Git commit author email", "nomad-changelog@localhost")

	config.WriteString(fmt.Sprintf("url = \"%s\"\n", gitURL))
	config.WriteString(fmt.Sprintf("branch = \"%s\"\n", branch))
	config.WriteString(fmt.Sprintf("auth_method = \"%s\"\n", authMethod))
	config.WriteString(fmt.Sprintf("local_path = \"%s\"\n", localPath))
	config.WriteString(fmt.Sprintf("repo_name = \"%s\"\n", repoName))
	config.WriteString(fmt.Sprintf("author_name = \"%s\"\n", authorName))
	config.WriteString(fmt.Sprintf("author_email = \"%s\"\n", authorEmail))

	if authMethod == "token" || authMethod == "auto" {
		config.WriteString("# token = \"\"  # Or set GITHUB_TOKEN/GH_TOKEN environment variable\n")
	}
}

func configureGitHubAPIBackend(reader *bufio.Reader, config *strings.Builder) {
	fmt.Println()
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println("🔧 GitHub API Backend Configuration")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()

	fmt.Println("For repository: github.com/myorg/nomad-jobs")
	fmt.Println("  • Owner: myorg")
	fmt.Println("  • Repo:  nomad-jobs")
	fmt.Println()

	owner := prompt(reader, "GitHub owner (org or username)", "")
	repo := prompt(reader, "Repository name", "")
	branch := prompt(reader, "Branch", "main")

	authorName := prompt(reader, "Git commit author name", "nomad-changelog")
	authorEmail := prompt(reader, "Git commit author email", "nomad-changelog@localhost")

	config.WriteString(fmt.Sprintf("owner = \"%s\"\n", owner))
	config.WriteString(fmt.Sprintf("repo = \"%s\"\n", repo))
	config.WriteString(fmt.Sprintf("branch = \"%s\"\n", branch))
	config.WriteString(fmt.Sprintf("author_name = \"%s\"\n", authorName))
	config.WriteString(fmt.Sprintf("author_email = \"%s\"\n", authorEmail))
	config.WriteString("# token = \"\"  # Or set GITHUB_TOKEN/GH_TOKEN environment variable\n")
}

// Helper functions for interactive prompts

func prompt(reader *bufio.Reader, question, defaultValue string) string {
	if defaultValue != "" {
		fmt.Printf("%s [%s]: ", question, defaultValue)
	} else {
		fmt.Printf("%s: ", question)
	}

	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(input)

	if input == "" {
		return defaultValue
	}
	return input
}

func promptChoice(reader *bufio.Reader, question string, choices []string, defaultChoice string) string {
	for {
		result := prompt(reader, question+" ("+strings.Join(choices, "/")+")", defaultChoice)

		// Check if result is valid
		for _, choice := range choices {
			if result == choice {
				return result
			}
		}

		fmt.Printf("Invalid choice. Please select one of: %s\n", strings.Join(choices, ", "))
	}
}

func promptYesNo(reader *bufio.Reader, question string, defaultYes bool) bool {
	defaultStr := "y/N"
	if defaultYes {
		defaultStr = "Y/n"
	}

	response := prompt(reader, question+" ("+defaultStr+")", "")
	response = strings.ToLower(response)

	if response == "" {
		return defaultYes
	}

	return response == "y" || response == "yes"
}
